### ISSUE TITLE
RMG fails with newer Python/Numpy versions due to type error

### ISSUE THREAD

**Issue by fabiolsilva** [SCECcode/bbp#17]
In newer Python/Numpy versions the RMG module fails due to some float indexes. Change these variable types to integer when they are used as array indexes and validate the change doesn't affect the results.

Here's the output of the unit test:

```
$ ./test_rmg.py
test_rmg (__main__.TestRMG) ... Running: cp /home/song/proj/GM_Sim/SCEC_BBP/bbp_17.3.0/bbp-17.3.0/bbp/tests/ref_data/song/test_whittier_song.src /home/song/proj/GM_Sim/SCEC_BBP/bbp_17.3.0/bbp_data/indata/8239555
---------------------------SONG Rupture Generator RMG---------------------------

### Step I: 2-point statistics
### generating 2D distributions of source parameters
### based on covariance matrix constructed from
### auto- and cross-correlation


=> Number of subfaults (fine grid): 10000
=> Number of subfaults (coarse grid): 729

=> Elapsed time for constructing Cm:       0.23
=> Elapsed time for Eigen decomposition:      39.89
=> Elapsed time for Cholesky Factorization:       0.15
ERROR

======================================================================
ERROR: test_rmg (__main__.TestRMG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rmg.py", line 59, in test_rmg
    rmg.run()
  File "/home/song/proj/GM_Sim/SCEC_BBP/bbp_17.3.0/bbp-17.3.0/bbp/comps/rmg.py", line 1284, in run
    self.gen_rup()
  File "/home/song/proj/GM_Sim/SCEC_BBP/bbp_17.3.0/bbp-17.3.0/bbp/comps/rmg.py", line 994, in gen_rup
    self.gen_dist()
  File "/home/song/proj/GM_Sim/SCEC_BBP/bbp_17.3.0/bbp-17.3.0/bbp/comps/rmg.py", line 816, in gen_dist
    (rup["nz1"], rup["nx1"]), order='F')
  File "/usr/local/lib/python-2.7.13/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python-2.7.13/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python-2.7.13/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: 'float' object cannot be interpreted as an index

----------------------------------------------------------------------
Ran 1 test in 40.599s

FAILED (errors=1)
```

**Comment by fabiolsilva** [comment]
This issue was fixed as per commit d2aa40cc5eefb2468a31357ca51907d49a7ab506
